# Gradle Properties
org.gradle.jvmargs = -Xmx6G -Dfile.encoding=UTF-8

# Source Options
# Use Lombok annotation processor
use_lombok_ap = true
lombok_version = 1.18.44

# Compilation Options
generate_sources_jar = true
generate_javadocs_jar = false

# Testing
enable_junit_testing = false
show_testing_output = false

# Shadow
enable_shadow = false

# Set this to true if you want to use old LWJGL2 methods.
# WARNING: Using LWJGL2 is no longer recommend, and some methods in LWJGL2 will be unavailable.
enable_lwjglx = true

# Mod Information
mod_version = 1.23.3
root_package = github.kasuminova.novaeng
mod_id = novaeng_core
mod_name = Nova Engineering: Core

# Mod Metadata (Optional)
mod_description = 新星工程计划核心模组。
mod_url = https://github.com/NovaEngineering-Source/NovaEngineering-Core
mod_update_json =
# Delimit authors with commas. Eg: Author1,Author2
mod_authors = Kasumi_Nova
mod_credits =
# Path to a png file. Eg: assets/modid/logo.png
mod_logo_path =

# Catalogue Extra Metadata (Optional)
mod_license =
mod_issue_tracker_url =
# Path to a square png file
mod_icon_path =
# An item to be rendered as the mod icon in Catalogue mod list,
# Formatted as modid:item_name(:meta)
mod_icon_item =
# Path to a 512x256 png file
mod_background_path =

# Run Configurations
# If multiple arguments/tweak classes are stated, use spaces as the delimiter
minecraft_username = Kasumi_Nova
extra_jvm_args =
enable_foundation_debug = false

# Maven Publishing (Provide secret: MAVEN_USER, MAVEN_PASS)
publish_to_maven = false
publish_to_jitpack = false
# Good for debugging artifacts before uploading to remote maven
# GitHub actions won't run if this is true, test this by running the task `publishToMavenLocal`
publish_to_local_maven = false
maven_name = ${mod_name}
maven_url =
maven_group = ${root_package}
maven_artifact_id = ${mod_id}
maven_developer_id =
maven_developer_name =
maven_license_name = ${mod_license}
maven_license_url =
maven_scm_url = ${mod_url}
jitpack_group =
jitpack_artifact_id =
jitpack_version =

# If any properties changes below this line, refresh gradle again to ensure everything is working correctly.
# ----------------------------------------------------------------------------------------------------------------------

# Access Transformers
# A way to change visibility of Minecraft's classes, methods and fields
# AT files should be in the root of src/main/resources with the filename formatted as: `mod_id_at.cfg`
# Use the property `access_transformer_locations` to state custom AT files if you aren't using the default `mod_id_at.cfg` location
# WARNING: Use MCP name in AT file. Unimined will remap it to srg name when building.
use_access_transformer = false
access_transformer_locations = ${mod_id}_at.cfg

# Coremods
# The most powerful way to change java classes at runtime, it is however very primitive with little documentation.
# Change the property `coremod_includes_mod` to false if your coremod doesn't have a @Mod annotation
is_coremod = true
coremod_includes_mod = true
coremod_plugin_class_name = github.kasuminova.novaeng.mixin.NovaEngCoreEarlyMixinLoader

# AssetMover
# Convenient way to allow downloading of assets from official vanilla Minecraft servers, CurseForge, or any direct links
# Documentation: https://github.com/CleanroomMC/AssetMover
use_asset_mover = false
asset_mover_version = 2.5
